### ISSUE TITLE
Clang build error with BOOST_THREAD_ATTRIBUTE_MAY_ALIAS

### ISSUE THREAD

**Issue by egorpugin** [boostorg/thread#145]
Clang output:
```
-c src/pthread/thread.cpp
In file included from src/pthread/thread.cpp:17:
In file included from include/boost/thread/once.hpp:20:
include/boost/thread/pthread/once_atomic.hpp:91:5: error: unknown type name 'BOOST_THREAD_ATTRIBUTE_MAY_ALIAS'
    BOOST_THREAD_ATTRIBUTE_MAY_ALIAS thread_detail::atomic_int_type storage;
    ^
include/boost/thread/pthread/once_atomic.hpp:91:53: error: non-friend class member 'atomic_int_type' cannot have a qualified name
    BOOST_THREAD_ATTRIBUTE_MAY_ALIAS thread_detail::atomic_int_type storage;
                                     ~~~~~~~~~~~~~~~^
include/boost/thread/pthread/once_atomic.hpp:91:68: error: expected ';' at end of declaration list
    BOOST_THREAD_ATTRIBUTE_MAY_ALIAS thread_detail::atomic_int_type storage;
                                                                   ^
include/boost/thread/pthread/once_atomic.hpp:100:52: error: no member named 'storage' in 'boost::once_flag'
      return reinterpret_cast< atomic_type& >(flag.storage);
                                              ~~~~ ^
```

See these lines https://github.com/boostorg/thread/blob/develop/include/boost/thread/detail/config.hpp#L20

It's suspicious that in `#ifndef` we define macro to nothing and then instantly set it to `MAY_ALIAS`.
Maybe there's missing `#else`?

I have a custom build (b2 is not used), so it's possible that I could miss some flags set.

**Comment by viboes** [comment]
This has been introduced in https://github.com/boostorg/thread/commit/23e7135f2c5f81b0192700a2c5de82599916d3c5#diff-54af14da6bc000f779c91e3087132068

Please, could you just try with
```
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
```

Andrey, what do you think?

**Comment by viboes** [comment]
`BOOST_THREAD_DETAIL_USE_ATTRIBUTE_MAY_ALIAS` is not used anymore.

I suspect that BOOST_MAY_ALIAS is not defined on your configuration.

Please, could you check if it is defined. If not could you try
```
#ifdef BOOST_MAY_ALIAS
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
#else
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS
#endif
```

**Comment by egorpugin** [comment]
I empty-defined BOOST_THREAD_ATTRIBUTE_MAY_ALIAS and it works for me. It's ok as a workaround. (Did not try your suggestion.)

**Comment by viboes** [comment]
Obviously, I can not define it as empty :)
Please give a try to my last suggestion:
```
#ifdef BOOST_MAY_ALIAS
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
#else
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS
#endif
```

**Comment by egorpugin** [comment]
It works.

**Comment by viboes** [comment]
Great, I will fix it.

Thanks for reporting and supporting the test.

**Comment by egorpugin** [comment]
Ok, thanks!

**Comment by viboes** [comment]
The issue comes from the fact that BOOST_MAY_ALIAS is not always defined

```
// Type aliasing hint.
#if __has_attribute(__may_alias__)
#  define BOOST_MAY_ALIAS __attribute__((__may_alias__))
#endif
```

Wondering if  this should be

```
// Type aliasing hint.
#if __has_attribute(__may_alias__)
#  define BOOST_MAY_ALIAS __attribute__((__may_alias__))
#else
#  define BOOST_MAY_ALIAS
#endif
```

but BOOST_MAY_ALIAS is not documented.

I've created a Boost.Config ticket. https://svn.boost.org/trac10/ticket/13211

**Comment by viboes** [comment]
It is weird. Please could you confirm you have this code in file /boost/config/detail/sufix.hpp?

```
#if !defined(BOOST_MAY_ALIAS)
#  define BOOST_NO_MAY_ALIAS
#  define BOOST_MAY_ALIAS
#endif
```

**Comment by viboes** [comment]
BTW, which version are you using?

**Comment by egorpugin** [comment]
1.65.0

**Comment by viboes** [comment]
I would need the output of the pre-processor, as I don't see what is wrong.

**Comment by egorpugin** [comment]
In `include/boost/thread/detail/config.hpp#L20` you have now:
```
#if BOOST_MAY_ALIAS // == #if !!BOOST_MAY_ALIAS
#define BOOST_THREAD_DETAIL_USE_ATTRIBUTE_MAY_ALIAS // define to nothing
#endif
#define BOOST_THREAD_DETAIL_USE_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS // unconditional may alias
```

**Comment by viboes** [comment]
This is not what I see.
```
#if !defined(BOOST_NO_MAY_ALIAS)

  // GCC since 3.3 and some other compilers have may_alias attribute that helps
  // to alleviate optimizer issues with regard to violation of the strict aliasing rules.

  #define BOOST_THREAD_DETAIL_USE_ATTRIBUTE_MAY_ALIAS
#endif
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
```

See https://github.com/boostorg/thread/blob/develop/include/boost/thread/detail/config.hpp#L20

**Comment by egorpugin** [comment]
Yes, but after simplification? You have double negation and get `#ifdef BOOST_MAY_ALIAS`.
Next, no matter what's inside of this ifdef, you always assign `BOOST_MAY_ALIAS` to `BOOST_THREAD_ATTRIBUTE_MAY_ALIAS`. Whole ifdef does not make sense.

Correct me if I'm getting something wrong in this small piece of code (preprocessor).

**Comment by viboes** [comment]
There are two symbols `BOOST_NO_MAY_ALIAS` and  `BOOST_MAY_ALIAS`. The last is always defined. The fist not.

**Comment by egorpugin** [comment]
I see, thanks.

**Comment by viboes** [comment]
So I don't understand where is the problem. Why is there a compile error?
Could you add the command line and the preprocessed output (flag -E)?

**Comment by egorpugin** [comment]
Sure.

Full command and preprocessed output:
```$ cd /Users/egor/.cppan/storage/obj/3b/8a/68a4/build/f7add531/cppan/3b8a68a4 && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_DYN_LINK -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_USE_DLL -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_USE_DLL -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_USE_DLL -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_USE_DLL -DBOOST_THREAD_BUILDING_THE_LIB -DBOOST_THREAD_BUILD_DLL -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_SOURCE -DBOOST_THREAD_USE_DLL -DCPPAN -DCPPAN_API_pvt_cppan_demo_boost_atomic_1_65_0=CPPAN_SYMBOL_IMPORT -DCPPAN_API_pvt_cppan_demo_boost_chrono_1_65_0=CPPAN_SYMBOL_IMPORT -DCPPAN_API_pvt_cppan_demo_boost_date_time_1_65_0=CPPAN_SYMBOL_IMPORT -DCPPAN_API_pvt_cppan_demo_boost_system_1_65_0=CPPAN_SYMBOL_IMPORT -DCPPAN_API_pvt_cppan_demo_boost_thread_1_65_0=CPPAN_SYMBOL_EXPORT -DCPPAN_BUILD -DCPPAN_CONFIG=\"91a9a0e5\" -DCPPAN_SYMBOL_EXPORT="" -DCPPAN_SYMBOL_IMPORT="" -DHAVE_SIZE_T=1 -DHAVE_VOID_P=1 -DPACKAGE=\"pvt.cppan.demo.boost.thread\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_BUILD_CONFIG=\"Release\" -DPACKAGE_COPYRIGHT_YEAR=2017 -DPACKAGE_NAME=\"pvt.cppan.demo.boost.thread\" -DPACKAGE_NAME_LAST=\"thread\" -DPACKAGE_STRING=\"3b8a68a4\" -DPACKAGE_URL=\"\" -DPACKAGE_VERSION=\"1.65.0\" -DSIZEOF_SIZE_T=8 -DSIZEOF_VOID_P=8 -DSIZE_OF_SIZE_T=8 -DSIZE_OF_VOID_P=8 -D_3b8a68a4_EXPORTS @CMakeFiles/3b8a68a4.dir/includes_CXX.rsp -O3 -DNDEBUG -fPIC   -Wno-macro-redefined -c /Users/egor/.cppan/storage/src/3b/8a/68a4/src/pthread/thread.cpp -E > thread.pp```


[thread.pp.zip](https://github.com/boostorg/thread/files/1315682/thread.pp.zip)

**Comment by viboes** [comment]
It is weird. We have

```
    BOOST_MAY_ALIAS thread_detail::atomic_int_type storage;
```

When we have 

```
#if !defined(BOOST_MAY_ALIAS)
#  define BOOST_NO_MAY_ALIAS
#  define BOOST_MAY_ALIAS
#endif
// ....
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
```

How is it that `BOOST_MAY_ALIAS`has not been replaced?

**Comment by viboes** [comment]
Anyway, I'll commit

```
#ifdef BOOST_MAY_ALIAS
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS BOOST_MAY_ALIAS
#else
#define BOOST_THREAD_ATTRIBUTE_MAY_ALIAS
#endif
```

As it works for you.

**Comment by viboes** [comment]
https://github.com/boostorg/thread/commit/1c51b5d9b8d24852ad208ab9e3e134fdce7c0d97

**Comment by egorpugin** [comment]
Thanks!
Should I close?

**Comment by viboes** [comment]
No problem, I prefer to close once I have do the merge to master.
